#!/bin/bash

docker run --rm -v `pwd`:/netifaces quay.io/pypa/manylinux1_x86_64 /netifaces/makewheels.sh
docker run --rm -v `pwd`:/netifaces quay.io/pypa/manylinux1_i686 linux32 /netifaces/makewheels.sh
ls wheelhouse/
