C:\Python27\python.exe setup.py clean bdist_egg bdist_wininst bdist_wheel %*
C:\Python34\python.exe setup.py clean bdist_egg bdist_wininst bdist_wheel %*
C:\Python35\python.exe setup.py clean bdist_egg bdist_wininst bdist_wheel %*
C:\Python36\python.exe setup.py clean bdist_egg bdist_wininst bdist_wheel %*
C:\Python37\python.exe setup.py clean bdist_egg bdist_wininst bdist_wheel %*
C:\Python38\python.exe setup.py clean bdist_egg bdist_wininst bdist_wheel %*
C:\Python27_32\python.exe setup.py clean bdist_egg bdist_wininst bdist_wheel %*
C:\Python34_32\python.exe setup.py clean bdist_egg bdist_wininst bdist_wheel %*
C:\Python35_32\python.exe setup.py clean bdist_egg bdist_wininst bdist_wheel %*
C:\Python36_32\python.exe setup.py clean bdist_egg bdist_wininst bdist_wheel %*
C:\Python37_32\python.exe setup.py clean bdist_egg bdist_wininst bdist_wheel %*
C:\Python38_32\python.exe setup.py clean bdist_egg bdist_wininst bdist_wheel %*
